spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=poketavern;trustServerCertificate=true
    username: sa
    password: '@StrongPass123'
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: create-drop